# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ad81eead6b59acaa4e89f227c9e76949ad03d133dc82cb94f88c2c7485e43df5476be5fbe08c4d4d26e07aa660d8c65a4d08ff2ce71878eedbc5b562310db5a

test:
  secret_key_base: 315d22475b1a9d092d746b5fe1ddd283526c1a2dfe16a9ed7de5a7cd89ac798f403b9fe8c9807ed49fefeaac1e1e3698ec7d5c7e9837a542396ceb68d3690f5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
